name: 'Setup MacPorts'
description: 'Setup MacPorts and add it to PATH'
inputs:
  macports-version:  # id of input
    description: 'The MacPorts version to install.'
    required: true
    default: ''
outputs:
  time: # output will be available to future steps
    description: 'The current time after waiting'
runs:
  using: 'node16'
  main: 'dist/index.js'
