name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test-latest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
    - run: port version

  test-specific:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        macports-version: "2.7.2"
    - run: port version
